version: "2"
linters:
  enable:
    - misspell
    - revive
  settings:
    misspell:
      ignore-rules:
        - strat
    revive:
      severity: error
      rules:
        - name: exported
        - name: if-return
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'exported: type name will be used as (.+) by other packages, and that stutters; consider calling this (.+)'
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
