apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: libvirt-provider
      labels:
        control-plane: controller-manager
    spec:
      initContainers:
        - name: check-prerequisites
          image: ubuntu
          securityContext:
            privileged: true
          command: [ '/bin/bash', '-c' ]
          env:
            - name: USER
              value: "libvirt-provider"
            - name: USER_ID
              value: "65532"
            - name: USER_GROUP
              value: "libvirt-provider"
            - name: USER_GROUP_ID
              value: "65532"
            - name: LIBVIRT_PROVIDER_DIR
              value: "/var/lib/libvirt-provider"
            - name: LIBVIRT_GROUP
              value: "libvirt"
            - name: LIBVIRT_QEMU_USER
              value: "libvirt-qemu"
            - name: LIBVIRT_QEMU_GROUP
              value: "libvirt-qemu"
            - name: DEPENDENCIES
              value: "libvirt-daemon-system libvirt-clients ovmf ceph-common"
          args:
            - |
              IFS=' ' read -r -a dependencies <<< "$DEPENDENCIES"
              for dependency in "${dependencies[@]}"; do
                if ! dpkg --root=/host-root --get-selections | grep -E "^${dependency}\s+install$" -q; then
                  echo "Error: $dependency is not installed."
                  exit 1
                fi
              done
              if ! getent group ${LIBVIRT_GROUP} > /dev/null; then
                  echo "Error: ${LIBVIRT_GROUP} group does not exist."
                  exit 1
              fi
              if ! getent group ${LIBVIRT_QEMU_GROUP} > /dev/null; then
                  echo "Error: ${LIBVIRT_QEMU_GROUP} group does not exist."
                  exit 1
              fi
              if ! id -u ${USER} > /dev/null; then
                  echo "Error: ${USER} user does not exist."
                  exit 1
              fi
              if ! getent group ${USER_GROUP} > /dev/null; then
                  echo "Error: ${USER_GROUP} group does not exist."
                  exit 1
              fi
              if ! id -nG ${USER} 2>/dev/null | grep -qw ${LIBVIRT_GROUP}; then
                  echo "Error: ${USER} is not a member of ${LIBVIRT_GROUP} group."
                  exit 1
              fi
              if ! id -nG ${LIBVIRT_QEMU_USER} 2>/dev/null | grep -qw ${USER_GROUP}; then
                  echo "Error: ${LIBVIRT_QEMU_USER} is not a member of ${USER_GROUP} group."
                  exit 1
              fi
              if [ ! -d "${LIBVIRT_PROVIDER_DIR}" ]; then
                  echo "Error: ${LIBVIRT_PROVIDER_DIR} directory does not exist."
                  exit 1
              fi
              if [ "$(stat -c '%U' ${LIBVIRT_PROVIDER_DIR})" != "${USER}" ]; then
                  echo "Error: ${LIBVIRT_PROVIDER_DIR} is not owned by ${USER}."
                  exit 1
              fi
              if [ "$(stat -c '%G' ${LIBVIRT_PROVIDER_DIR})" != "${USER_GROUP}" ]; then
                  echo "Error: ${LIBVIRT_PROVIDER_DIR} group is not ${USER_GROUP}."
                  exit 1
              fi
              if [ "$(stat -c '%a' ${LIBVIRT_PROVIDER_DIR})" != "755" ]; then
                  echo "Error: ${LIBVIRT_PROVIDER_DIR} permissions are not 0755."
                  exit 1
              fi
          volumeMounts:
            - name: etc
              mountPath: /etc
            - name: libvirt-provider
              mountPath: /var/lib/libvirt-provider
            - name: host-dpkg
              mountPath: /host-root/var/lib/dpkg
              readOnly: true
      containers:
        - command:
            - /machinepoollet
          args:
            - --leader-elect
          image: machinepoollet:latest
          name: manager
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - mountPath: /var/run
              name: var-run
        - command:
            - /libvirt-provider
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: libvirt-provider:latest
          name: provider
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8181
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - name: var-run
              mountPath: /var/run
            - mountPath: /var/lib/libvirt-provider
              name: libvirt-provider
            - mountPath: /var/run/libvirt
              name: libvirt
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus
            - mountPath: /usr/share/misc/pci.ids
              name: pci-ids
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: var-run
          emptyDir: { }
        - name: libvirt
          hostPath:
            path: /var/run/libvirt
        - name: libvirt-provider
          hostPath:
            path: /var/lib/libvirt-provider
            type: Directory
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: dbus
          hostPath:
            path: /var/run/dbus/system_bus_socket
        - name: pci-ids
          hostPath:
            path: /usr/share/misc/pci.ids
            type: File
        - name: etc
          hostPath:
            path: /etc
            type: Directory
        - name: host-dpkg
          hostPath:
            path: /var/lib/dpkg
            type: Directory
