apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Adds namespace to all resources.
namespace: libvirt-provider-system

namePrefix: libvirt-provider-dev-

resources:
- ../manager
- ../rbac
- machineclass-extra-huge.yaml
- machineclass-t3-small.yaml
- machineclass-x3-xlarge.yaml

configMapGenerator:
- files:
  - machineclasses.yaml
  name: machineclasses

patches:
- path: manager.patch.yaml
  target:
    group: apps
    kind: DaemonSet
    name: controller-manager
    version: v1
